routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true, 'register' => false]);
Route::get('/', 'HomeController@welcome')->name('welcome');
Route::middleware(['auth'])->prefix('admin')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('practices', 'PracticeController');
    Route::resource('employees', 'EmployeeController');
    Route::resource('fop', 'FieldsOfPracticeController');
});

app/Models/Practice.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\FieldsOfPractice;
use App\Models\Employee;

class Practice extends Model
{
    protected $guarded = [];


    public function tags()
    {
        return $this->belongsToMany(FieldsOfPractice::class, 'fop_practice', 'practice_id', 'fop_id')->withTimestamps();
    }

    public function employees()
    {
        return $this->hasMany(Employee::class);
    }

    public function getAvatarAttribute()
    {
        return url($this->logo);
    }

    public function getFieldsAttribute()
    {
        return implode($this->tags->pluck('tag')->toArray(), ', ');
    }
}

app/Http/Controllers/PracticeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PracticeRequest;
use App\Http\Resources\PracticeResources;
use App\Models\FieldsOfPractice;
use App\Models\Practice;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use App\Traits\MyTraits;

class PracticeController extends Controller
{
    use MyTraits;

    public function __construct()
    {
        $this->middleware('auth', ['except' => ['practices']]);
    }

    public function practices()
    {
        return PracticeResources::collection(Practice::all());
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $practices = Practice::with('tags')->orderBy('id', 'desc')->paginate(5);
        return view(request()->route()->getName())->with('practices', $practices);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $tags = FieldsOfPractice::orderBy('tag', 'asc')->get();
        return view(request()->route()->getName())->with('tags', $tags);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $practice = Practice::create([
            'name' => $request->name,
            'email' => $request->email,
            'website' => $request->website,
            'logo' => $this->storeLogo($request),
        ]);
        $practice->tags()->sync($request->tags);
        return redirect()->route('practices.index')->with('success', 'Stored successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Practice  $practice
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $practice = Practice::with('employees')->whereId($id)->first();
        return view(request()->route()->getName())->with('practice', $practice);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Practice  $practice
     * @return \Illuminate\Http\Response
     */
    public function edit(Practice $practice)
    {
        $tags = FieldsOfPractice::orderBy('tag', 'asc')->get();
        return view(request()->route()->getName())->with('practice', $practice)->with('tags', $tags);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Practice  $practice
     * @return \Illuminate\Http\Response
     */
    public function update(PracticeRequest $request, Practice $practice)
    {

        $practice->update([
            'name' => $request->name,
            'email' => $request->email,
            'website' => $request->website,
        ]);

        if ($request->has('logo')) {
            $practice->logo = $this->updateLogo($request);
            $practice->save();
        }


        $practice->tags()->sync($request->tags);
        return redirect()->route('practices.index')->with('success', 'Updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Practice  $practice
     * @return \Illuminate\Http\Response
     */
    public function destroy(Practice $practice)
    {
        $practice->delete();
        return redirect()->route('practices.index')->with('success', 'Deleted successfully');
    }
}

resources/views/practices/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
 @component('components.forms',['type'=>'Create new practice'])
 @slot('form')
        <form  method="POST" action="{{route('practices.store')}}" enctype="multipart/form-data">
            {{csrf_field()}}
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control"  placeholder="Enter name" value=""
                    required name="name">
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control"  placeholder="Enter email" value=""
                    required name="email">
            </div>
            <div class="form-group">
                <label for="name">Website</label>
                <input type="text" class="form-control"  placeholder="Enter `website link" value=""
                    name="website">
            </div>
            <div class="form-group">
                <label for="logo">Logo</label>
                <input type="file" name="logo" class="form-control">
            </div>
            <div class="form-group">
                @foreach($tags as $tag)
                <div class="form-check">
                    <label>
                        <input type="checkbox" name="tags[]"  value="{{$tag->id}}"> <span class="label-text text-capitalize">{{$tag->tag}}</span>
                    </label>
                </div>
                @endforeach
            </div>
             <div class="form-group text-center">
               <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
        @endslot
        @endcomponent
    </div>
@endsection

resources/views/practices/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
  @component('components.forms',['type'=>'Create new practice'])
    @slot('form')
  
        <form  method="POST" action="{{route('practices.update',$practice->id)}}"
            enctype="multipart/form-data">
            {{csrf_field()}}
            @method('PUT')
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control"  placeholder="Enter name"
                    value="{{ $practice->name }}" required name="name">
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control"  placeholder="Enter email"
                    value="{{ $practice->email }}" required name="email">
            </div>
            <div class="form-group">
                <label for="website">Website</label>
                <input type="text" class="form-control"  placeholder="Enter website link"
                    value="{{ $practice->website }}" name="website">
            </div>
            <div class="form-group">
                <label for="name">Website</label>
                <img src="{{$practice->avatar}}" class="logo">
                <input type="file" name="logo" class="form-control">
            </div>
            <div class="form-group">
                @foreach($tags as $tag)
                
                <div class="form-check">
                    <label>         
                        <input type="checkbox" name="tags[]"  value="{{$tag->id}}" @if(in_array($tag->id, $practice->tags->pluck('id')->toArray())) checked @endif> <span class="label-text text-capitalize">{{$tag->tag}}</span>
                    </label>
                </div>
                @endforeach
            </div>
            <div class="form-group text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
    @endslot
    @endcomponent
    </div>
@endsection

resources/views/practices/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    @component('components.notification') @endcomponent
    @component('components.table',['route'=>'practices.create','type'=>'Practices view'])
    @slot('table')
    @if(sizeof($practices)>0)
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Logo</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Website</th>
                <th scope="col">Tags</th>
                <th scope="col">Edit</th>
            </tr>
        </thead>
        <tbody>

            @foreach($practices as $practice)
            <tr class="">
                <th scope="row">{{$practice->id}}</th>
                <td><img class="logo" src="{{$practice->avatar}}" /></td>
                <td><a class="text-capitalize" href="{{route('practices.show',$practice->id)}}">{{$practice->name}}</a>
                </td>
                <td>{{$practice->email}}</td>

                <td><a href="{{$practice->website}}" target="_blank">Link</a></td>
                <td><span class="text-success"> {{$practice->fields}}</span></td>
                <td><a href="{{route('practices.edit',['id'=>$practice->id])}}" class="btn btn-sm btn-primary">Edit</a>
                </td>
            </tr>
            @endforeach

        </tbody>
    </table>
    @else
    <div class="col-md-12 alert alert-danger text-center">No records</div>
    @endif
    @endslot
    @slot('pagination')
    {{ $practices->links() }}
    @endslot
    @endcomponent
</div>
@endsection

resources/views/practices/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-end">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="card-title mb-4">
                        <div class="d-flex justify-content-start">
                            <div class="image-container">
                                <img src="{{$practice->avatar}}" id="imgProfile" style="width: 150px; height: 150px"
                                    class="img-thumbnail" />
                            </div>
                            <div class="userData ml-3">
                                <h2 class="d-block" style="font-size: 1.5rem; font-weight: bold">
                                    <a href="{{route('practices.show',$practice->id)}}">{{$practice->name}}</a></h2>
                                <h6 class="d-block">
                                    <span class="font-weight-bold">Email:</span>
                                    {{$practice->email}}</h6>
                                <h6 class="d-block"> <span class="font-weight-bold">Tags:</span> {{$practice->fields}}
                                </h6>
                                <h6 class="d-block"> <span class="font-weight-bold">External link:</span> <a
                                        href="{{$practice->website}}" target="_blank">Link</a></h6>
                            </div>
                            <div class="ml-auto">
                                <input type="button" class="btn btn-primary d-none" id="btnDiscard"
                                    value="Discard Changes" />
                            </div>
                            <div class="row justify-content-center " style="height:20px">
                                <a href="{{route('practices.index')}}" class="btn mr-1 btn-success">All</a>
                                <a href="{{route('practices.edit',$practice->id)}}"
                                    class="btn mr-1 btn-primary">Edit</a>
                                <form action="{{route('practices.destroy',['id'=>$practice->id])}}" method="POST">
                                    @method('delete')
                                    @csrf
                                    <button type="submit" class="btn mr-1 btn-danger">Delete</button>
                                </form>

                            </div>
                        </div>

                    </div>

                    <div class="row">
                        <div class="col-12">
                            <ul class="nav nav-tabs mb-4" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="basicInfo-tab" data-toggle="tab" href="#basicInfo"
                                        role="tab" aria-controls="basicInfo" aria-selected="true">Employees
                                        ({{$practice->employees->count()}})</a>
                                </li>

                            </ul>
                            <div class="tab-content ml-1" id="myTabContent">
                                <div class="tab-pane fade show active" id="basicInfo" role="tabpanel"
                                    aria-labelledby="basicInfo-tab">
                                    @foreach($practice->employees as $employe)
                                    <div class="row">
                                        <div class="col-sm-12 ">
                                            <a href="{{route('employees.show',$employe->id)}}" class="text-capitalize">
                                                {{$employe->first_name}}
                                                {{$employe->last_name}}
                                            </a>

                                        </div>
                                        <div class="col-md-12 col-6">
                                            {{$employe->email}} - {{$employe->phone}}
                                        </div>
                                    </div>
                                    <hr />
                                    @endforeach
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection