routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true, 'register' => false]);
Route::get('/', 'HomeController@welcome')->name('welcome');
Route::middleware(['auth'])->prefix('admin')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('practices', 'PracticeController');
    Route::resource('employees', 'EmployeeController');
    Route::resource('fop', 'FieldsOfPracticeController');
});

resources/views/fop/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    @component('components.forms',['type'=>'Create new fields of practice'])
    @slot('form')
    <form method="POST" action="{{route('fop.store')}}" enctype="multipart/form-data">
        {{csrf_field()}}
        <div class="form-group">
            <label for="name">Tag</label>
            <input type="text" class="form-control" placeholder="Enter tag" equired name="tag">
        </div>
        <div class="form-group text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
    @endslot
    @endcomponent
</div>
@endsection

resources/views/fop/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
      @component('components.forms',['type'=>'Update field of practice'])
    @slot('form')
        <form  method="POST" action="{{route('fop.update',$fop->id)}}"
            enctype="multipart/form-data">
            {{csrf_field()}}
            @method('PUT')
            <div class="form-group">
                <label for="name">Tag</label>
                <input type="text" class="form-control"  placeholder="Enter tag"
                    value="{{ $fop->tag }}" required name="tag">
            </div>
            <div class="form-group text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
        </form>
   @endslot
    @endcomponent
</div>
@endsection

resources/views/fop/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    @component('components.notification') @endcomponent
    @component('components.table',['route'=>'fop.create','type'=>'Fields of Practice view'])
    @slot('table')
    @if(sizeof($fops)>0)
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Tag</th>

                <th scope="col">Edit</th>
            </tr>
        </thead>
        <tbody>

            @foreach($fops as $fop)
            <tr class="">
                <th scope="row">{{$fop->id}}</th>
                <td><a class="text-capitalize" href="{{route('fop.show',$fop->id)}}">{{$fop->tag}}</a></td>
                <td><a href="{{route('fop.edit',['id'=>$fop->id])}}" class="btn btn-sm btn-primary">Edit</a></td>

            </tr>
            @endforeach
        </tbody>
    </table>
    @else
    <div class="col-md-12 alert alert-danger text-center">No records</div>
    @endif
    @endslot
    @slot('pagination')
    {{ $fops->links() }}
    @endslot
    @endcomponent
</div>
@endsection

resources/views/fop/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-end">
        <div class="col-12">
            <div class="card">

                <div class="card-body">
                    <div class="card-title mb-4">
                        <div class="d-flex justify-content-between">
                        <div>{{$fop->tag}}</div>
                            <div class="row justify-content-center " style="height:20px">
                                <a href="{{route('fop.index')}}" class="btn mr-1 btn-success">All</a>
                                <a href="{{route('fop.edit',$fop->id)}}"
                                    class="btn mr-1 btn-primary">Edit</a>
                                <form action="{{route('fop.destroy',['id'=>$fop->id])}}" method="POST">
                                    @method('delete')
                                    @csrf
                                    <button type="submit" class="btn mr-1 btn-danger">Delete</button>
                                </form>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12">
                            <ul class="nav nav-tabs mb-4" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="basicInfo-tab" data-toggle="tab" href="#basicInfo"
                                        role="tab" aria-controls="basicInfo" aria-selected="true">Practices ({{$fop->practices->count()}})</a>
                                </li>
                              
                            </ul>
                            <div class="tab-content ml-1" id="myTabContent">
                                <div class="tab-pane fade show active" id="basicInfo" role="tabpanel"
                                    aria-labelledby="basicInfo-tab">
                                    @foreach($fop->practices as $practice)
                                    <div class="row">
                                        <div class="col-sm-12 ">
                                            <a href="{{route('practices.show',$practice->id)}}" class="text-capitalize">
                                                Name: {{$practice->name}} <br> Email: {{$practice->email}}</a>
                                        </div>
                                        
                                    </div>
                                    <hr />
                                    @endforeach
                                </div>
                              
                            </div>
                        </div>
                    </div>


                </div>

            </div>
        </div>
    </div>
</div>
@endsection