routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true, 'register' => false]);
Route::get('/', 'HomeController@welcome')->name('welcome');
Route::middleware(['auth'])->prefix('admin')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('practices', 'PracticeController');
    Route::resource('employees', 'EmployeeController');
    Route::resource('fop', 'FieldsOfPracticeController');
});

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Practice;

class Employee extends Model
{
    protected $guarded = [];

    public function practice()
    {
        return $this->belongsTo(Practice::class);
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\EmployeeRequest;
use App\Models\Employee;
use App\Models\Practice;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::with('practice')->orderBy('id', 'desc')->paginate(10);
        return view(request()->route()->getName())->with('employees', $employees);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $practices = Practice::orderBy('name', 'asc')->get();
        return view(request()->route()->getName())->with('practices', $practices);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployeeRequest $request)
    {
        Employee::create($request->all());
        return redirect()->route('employees.index')->with('success', 'Stored successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $employee = Employee::with('practice')->whereId($id)->first();
        return view(request()->route()->getName())->with('employee', $employee);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        $practices = Practice::orderBy('name', 'asc')->get();
        return view(request()->route()->getName())->with('employee', $employee)->with('practices', $practices);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(EmployeeRequest $request, Employee $employee)
    {
        $employee->update($request->all());
        return redirect()->route('employees.index')->with('success', 'Updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        $employee->delete();
        return redirect()->route('employee.index')->with('success', 'Deleted successfully');
    }
}

resources/views/employees/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
     @component('components.forms',['type'=>'Create new employee'])
@slot('form')
        <form  method="POST" action="{{route('employees.store')}}" enctype="multipart/form-data">         
            <div class="form-group">
                {{csrf_field()}}
                <label for="name">Practice</label>
                <select name="practice_id" class="form-control">
                    @foreach($practices as $practice)                 
                    <option value="{{$practice->id}}">{{$practice->name}}</option>      
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label for="name">First Name</label>
                <input type="text" class="form-control" placeholder="Enter first name"
                   required name="first_name">
            </div>
            <div class="form-group">
                <label for="text">Last name</label>
                <input type="text" class="form-control" placeholder="Enter last name"
                    required name="last_name">
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" placeholder="Enter email" 
                    name="email">
            </div>
            <div class="form-group">
                <label for="email">Phone</label>
                <input type="text" class="form-control" placeholder="Enter phone" 
                    name="phone">
            </div>
            <div class="form-group text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
           
        </form>
   @endslot
    @endcomponent
</div>
@endsection

resources/views/employees/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    @component('components.forms',['type'=>'Edit employee'])
    @slot('form')
    <form method="POST" action="{{route('employees.update',$employee->id)}}" enctype="multipart/form-data">
        {{csrf_field()}}
        @method('PUT')
        <div class="form-group">
            <label for="name">Practice</label>
            <select name="practice_id" class="form-control">
                @foreach($practices as $practice)
                @if($practice->id==$employee->practice->id)
                <option value="{{$practice->id}}" selected="true">{{$practice->name}}</option>
                @else
                <option value="{{$practice->id}}">{{$practice->name}}</option>
                @endif
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label for="name">First Name</label>
            <input type="text" class="form-control" placeholder="Enter first name" value="{{ $employee->first_name }}"
                required name="first_name">
        </div>
        <div class="form-group">
            <label for="email">Last name</label>
            <input type="email" class="form-control" placeholder="Enter last name" value="{{ $employee->email }}"
                required name="last_name">
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="text" class="form-control" placeholder="Enter email" value="{{ $employee->email }}"
                name="email">
        </div>
        <div class="form-group">
            <label for="email">Phone</label>
            <input type="text" class="form-control" placeholder="Enter phone" value="{{ $employee->phone }}"
                name="phone">
        </div>
        <div class="form-group text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>

    </form>
    @endslot
    @endcomponent
</div>
@endsection

resources/views/employees/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  @component('components.notification') @endcomponent
     @component('components.table',['route'=>'employees.create','type'=>'Employees view'])
     @slot('table')
       @if(sizeof($employees)>0)
     <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Practices</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Phone</th>
                  
                    <th scope="col">Edit</th>
                  
                    
                </tr>
            </thead>
            <tbody>
              
                @foreach($employees as $employee)
                <tr class="">  
                    <th scope="row">{{$employee->id}}</th>
                    <td><a href="{{route('practices.show', $employee->practice->id)}}">{{$employee->practice->name}}</a></a></td>
                    <td><a href="{{route('employees.show', $employee->id)}}">{{$employee->first_name}}</a></td>
                    <td><a href="{{route('employees.show', $employee->id)}}">{{$employee->last_name}}</a></td>
                    <td>{{$employee->email}}</td>
                    <td>{{$employee->phone}}</td>
                    <td><a href="{{route('employees.edit',['id'=>$employee->id])}}" class="btn btn-sm btn-primary">Edit</a></td>
                    
                </tr>
                @endforeach
            </tbody>
        </table>
      
        @else
        <div class="col-md-12 alert alert-danger text-center">No records</div>
        @endif
         @endslot
         @slot('pagination')
    {{ $employees->links() }}
    @endslot
    @endcomponent
   
</div>
@endsection
  

resources/views/employees/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-end">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="card-title mb-4">
                        <div class="d-flex justify-content-between">
                           
                            <div class="userData ml-3">
                                <h2 class="d-block" style="font-size: 1.5rem; font-weight: bold"><a
                                        href="javascript:void(0);">{{$employee->first_name}} {{$employee->last_name}}</a></h2>
                                        <a href="mailto:{{$employee->email}}">{{$employee->email}}</a>
                                <h6 class="d-block">
                                <a href="tel:+{{$employee->phone}}">{{$employee->phone}}</a>    
                                </h6>
                                <h6 class="d-block"> <a href="{{route('practices.show',$employee->practice->id)}}" >{{$employee->practice->name}}</a> </h6>
                            </div>
                            <div>
                                <a href="{{route('employees.index')}}" class="btn btn-success">All</a>
                                <a href="{{route('employees.edit',$employee->id)}}" class="btn btn-primary">Edit</a>
                                <a href="{{route('employees.destroy',$employee->id)}}" class="btn btn-danger">Remove</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection